version: '2.4'

services:
  app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/app
    environment:
      - DEBUG=sample-express:*
      - NODE_ENV=development
      - MONGO_URI=mongodb://db:27017/smartphones
    depends_on:
      - db

  db:
    image: mongo

